workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      node: 22
      java: 17
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Set permissions
        script: chmod +x node_modules/.bin/cap
      - name: Capacitor sync
        script: node_modules/.bin/cap sync android
      - name: Set gradlew permission
        script: chmod +x android/gradlew
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
